# Teoria cuantica basica, observables y medidas

## Simule el primer sistema cuantico descrito en la seccion 4.1

##  El sistema debe calcular la probabilidad de encontrarlo en una posición en particular.

In [4]:
# Solución 
import numpy as np
def normalizar(datos):
    acumulado = 0
    for i in range(len(datos)):
        acumulado += modulo(datos[i])
    acumulado = acumulado ** (0.5)
    for i in range(len(datos)):
        datos[i] /= acumulado 
    return datos

def modulo(A):
    return np.abs(A) ** 2

def probsistlineal(estado, pos):
    if pos > len(estado):
        raise Exception("La posicion excede el tamaño del estado")
    estado = normalizar(estado)
    return modulo(estado[pos])


#Ejemplo sacado del libro
v1= np.array([[-3-1j],[-2j],[1j],[2j]])

#Prop en la posicion 1
posicion = 0
prob_1 = probsistlineal(v1,posicion)
print("La probabilidad es: ", prob_1)

#Prop en la posicion 2
posicion = 1
prob_2 = probsistlineal(v1,posicion)
print("La probabilidad es: ", prob_2)

#Prop en la posicion 3, pdt en esta posicion se compara con el resultado del libro y si coinciden
posicion = 2
prob_3 = probsistlineal(v1,posicion)
print("La probabilidad es: ", prob_3)

#Prop en la posicion 4
posicion = 3
prob_4 = probsistlineal(v1,posicion)
print("La probabilidad es: ", prob_4)

#Verificacion con la suma de las probabilidades
suma = (prob_1[0] + prob_2[0] + prob_3[0] + prob_4[0] )
print("La suma de las probabilidades es: ", suma)




La probabilidad es:  [0.52631579]
La probabilidad es:  [0.21052632]
La probabilidad es:  [0.05263158]
La probabilidad es:  [0.21052632]
La suma de las probabilidades es:  1.0


#   El sistema si se le da otro vector Ket debe buscar la probabilidad de transitar del primer vector al segundo.

In [5]:
#Solucion  
import numpy as np
def normalizar(datos):
    acumulado = 0
    for i in range(len(datos)):
        acumulado += modulo(datos[i])
    acumulado = acumulado ** (0.5)
    for i in range(len(datos)):
        datos[i] /= acumulado 
    return datos

def modulo(A):
    return np.abs(A) ** 2

def proba(matriz1, matriz2):
    matriz1 = normalizar(matriz1)
    matriz2 = normalizar(matriz2)
    producto_interno = np.dot(matriz1,np.conj(matriz2))
    prob = np.abs(producto_interno) ** 2
    return prob

#Ejemplo

v1= np.array([-3-1j , -2j , 1j ,2j])
v2 = np.array([4j, 2+8j, 3j, 9+6j])
probabilidad = proba(v1,v2)
print("La probabilidad es :", probabilidad)



La probabilidad es : 0.1756892230576441


# Complete los retos de programación del capitulo 4

## Amplitud de transición. El sistema puede recibir dos vectores y calcular la probabilidad de transitar de el uno al otro después de hacer la observación

In [7]:
# Solucion 
import numpy as np
def normalizar(datos):
    acumulado = 0
    for i in range(len(datos)):
        acumulado += modulo(datos[i])
    acumulado = acumulado ** (0.5)
    for i in range(len(datos)):
        datos[i] /= acumulado 
    return datos

def modulo(A):
    return np.abs(A) ** 2

def proba(matriz1, matriz2):
    matriz1 = normalizar(matriz1)
    matriz2 = normalizar(matriz2)
    producto_interno = np.dot(matriz1,np.conj(matriz2))
    prob = np.abs(producto_interno) ** 2
    return prob

#Ejemplo

v1= np.array([5j+2 , -2j , 1j ,2j])
v2 = np.array([1-4j, 2+8j, 3j, 9+6j])
probabilidad = proba(v1,v2)
print("La probabilidad es :", probabilidad)


La probabilidad es : 0.1359441257171365


## Ahora con una matriz que describa un observable y un vector ket, el sistema revisa que la matriz sea hermitiana, y si lo es, calcula la media y la varianza del observable en el estado dado.

In [9]:
# Solucion 
import numpy as np

def hermitian(matriz):
    is_hermitian = np.allclose(matriz, matriz.conj().T)
    return is_hermitian

def accionvecmat(matriz, ket):
    return np.dot(matriz, ket)

def multiplicacion(matriz, ket):
    return np.dot(matriz, ket)

def matrixXescalar(matriz, escalar):
    return matriz * escalar

def producto_interno(matriz1, matriz2):
    return np.dot(matriz1.conj().T, matriz2)

def restamatriz(matriz1, matriz2):
    return np.subtract(matriz1, matriz2)

def sumacomplejos(a, b):
    return a + b

def valoresperado(matriz, ket):
    if not hermitian(matriz):
        raise Exception("No se puede realizar la operacion debido a que la matriz no es hermitiana")
    else:
        return producto_interno(accionvecmat(matriz, ket), ket)[0][0]

def varianza(matriz, ket):
    if not hermitian(matriz):
        raise Exception("No se puede realizar la operacion debido a que la matriz no es hermitiana")
    else:
        identidad = np.identity(len(matriz))
        delta = restamatriz(matriz, matrixXescalar(valoresperado(matriz, ket), identidad))
        delta = multiplicacion(delta, delta)
        return producto_interno(accionvecmat(delta, ket), ket)[0][0]

# Ejemplo
matriz_hermitiana = np.array([[1, 2+1j],
                               [2-1j, 4]])

ket = np.array([[1], [2+1j]])

print("Valor esperado:", valoresperado(matriz_hermitiana, ket))
print("Varianza:", varianza(matriz_hermitiana, ket))



Valor esperado: (27+0j)
Varianza: (3057+0j)


##  El sistema calcula los valores propios del observable y la probabilidad de que el sistema transite a alguno de los vectores propios después de la observación.

In [34]:
# Solucion 
import numpy as np

def normalizar(datos):
    acumulado = 0
    for i in range(len(datos)):
        acumulado += modulo(datos[i])
    acumulado = acumulado ** 0.5
    for i in range(len(datos)):
        datos[i] = datos[i] / acumulado  # Convertir a tipo float para evitar error de casting
    return datos


def modulo(A):
    return np.abs(A) ** 2

def producto_interno(matriz1, matriz2):
    return np.dot(matriz1.conj().T, matriz2)

def vectsvalspropios(matriz):
    valores_propios, vectores_propios = np.linalg.eig(matriz)
    valores_propios_tuplas = [(np.real(valor), np.imag(valor)) for valor in valores_propios]
    vectores_propios = [np.expand_dims(vec, axis=1) for vec in vectores_propios]  # Asegurar que sean vectores columna
    return valores_propios_tuplas, vectores_propios



def transitar(estadoi, estadof):
    estadoi = normalizar(estadoi)
    estadof = normalizar(estadof)
    return producto_interno(estadof, estadoi)

# Ejemplo de uso:

# Definir una matriz observable hermitiana (3x3)
matriz_observable = np.array([[5, -1j, 2],
                              [1j, 3, 1+2j],
                              [2, 1-2j, 4]])

# Calcular valores y vectores propios
valores_propios, vectores_propios = vectsvalspropios(matriz_observable)

# Imprimir los valores propios
print("Valores propios del observable:")
for valor in valores_propios:
    print(valor)

# Definir un estado inicial
ket = np.array([[1], [0], [0]])

# Calcular la probabilidad de transición a cada vector propio
print("\nProbabilidad de transición a cada vector propio:")
for i, vector in enumerate(vectores_propios):
    probabilidad = transitar(ket, vector)
    print("Probabilidad de transitar al vector propio", i+1, ":", probabilidad)

Valores propios del observable:
(7.5979898266684724, 3.4189774283052523e-16)
(3.3371617243670233, 1.612079254282276e-16)
(1.0648484489645045, -5.901645840869009e-17)

Probabilidad de transición a cada vector propio:
Probabilidad de transitar al vector propio 1 : [[0.64396328+0.j]]
Probabilidad de transitar al vector propio 2 : [[0.11157138-0.42385912j]]
Probabilidad de transitar al vector propio 3 : [[0.62457547-0.05578569j]]


#  Se considera la dinámica del sistema. Ahora con una serie de matrices Un el sistema calcula el estado final a partir de un estado inicial.

In [64]:
# Solucion  

import numpy as np

def accionvecmat(matriz, ket):
    return np.dot(matriz, ket)

def unitaria(A):
    A_np = np.array(A)  # Convertir la lista A a una matriz NumPy
    res = np.matmul(np.conj(A_np.T), A_np)
    identidad = np.eye(len(res), dtype=np.complex128)
    return np.allclose(res, identidad)

def dinamicasistema(matrices_unitarias, estado_inicial, veces=1):
    estado_actual = estado_inicial
    for _ in range(veces):
        for matriz_unitaria in matrices_unitarias:
            if not unitaria(matriz_unitaria):
                print("Una de las matrices proporcionadas no es unitaria.")
            estado_actual = accionvecmat(matriz_unitaria, estado_actual)
    return estado_actual

# Definir algunas matrices unitarias y un estado inicial
matriz_unitaria1 = np.array([[0, 1, 0],
                              [1, 0, 0],
                              [0, 0, 1]])

matriz_unitaria2 = np.array([[1, 0, 0],
                              [0, 0, 1],
                              [0, 1, 0]])

estado_inicial = np.array([1, 0, 0])

# Aplicar las transformaciones unitarias al estado inicial
matrices_unitarias = [matriz_unitaria1, matriz_unitaria2]
estado_final = dinamicasistema(matrices_unitarias, estado_inicial)

print("Estado final después de la dinámica del sistema:", estado_final)


Estado final después de la dinámica del sistema: [0 0 1]


# REALICE LOS SIGUIENTES PROBLEMAS E INCLUYALOS COMO EJEMPLOS

## Solucion 4.3.1

In [46]:
def Ejercicio431():
    
    v1 = np.array([[1, 0], [0, 0]])
    observable_x = np.array([[(0, 0), (1, 0)], [(1, 0), (0, 0)]])
    vr = accionvecmat(observable_x, v1)
    vals, vects_x = vectsvalspropios(observable_x)
    print("Da el siguiente resultado despues de la observacion", vr)
    print("Los valores propios son ", vals, "\nvectores poropios son: ", vects_x)

Ejercicio431()

Da el siguiente resultado despues de la observacion [[[0 0]
  [1 0]]

 [[1 0]
  [0 0]]]
Los valores propios son  [(array([0., 0.]), array([0., 0.])), (array([1., 0.]), array([0., 0.]))] 
vectores poropios son:  [array([[[ 0.00000000e+000,  2.00416836e-292]],

       [[ 1.00000000e+000, -1.00000000e+000]]]), array([[[1., 0.]],

       [[0., 1.]]])]


## Solucion 4.3.2

In [50]:
def Ejercicio432():
    v1 = np.array([[1, 0], [0, 0]])
    observable = np.array([[(0, 0), (1, 0)], [(1, 0), (0, 0)]])
    vals, vects = vectsvalspropios(observable)
    for i in range(len(vects)):
        print(transitar(v1,vects[i]))
Ejercicio432()

[[[ 0.00000000e+000 -2.14748365e+009]]

 [[ 2.00416836e-292  2.14748365e+009]]]
[[[ 1.00000000e+00 -2.14748365e+09]]

 [[ 0.00000000e+00 -2.14748365e+09]]]


C:\Users\santiago.cordoba-d\AppData\Local\Temp\ipykernel_13124\674641486.py:10: RuntimeWarning: invalid value encountered in divide
  datos[i] = datos[i] / acumulado  # Convertir a tipo float para evitar error de casting
C:\Users\santiago.cordoba-d\AppData\Local\Temp\ipykernel_13124\674641486.py:10: RuntimeWarning: invalid value encountered in cast
  datos[i] = datos[i] / acumulado  # Convertir a tipo float para evitar error de casting
C:\Users\santiago.cordoba-d\AppData\Local\Temp\ipykernel_13124\674641486.py:10: RuntimeWarning: divide by zero encountered in divide
  datos[i] = datos[i] / acumulado  # Convertir a tipo float para evitar error de casting


## Solucion 4.4.1

In [58]:
def Ejercicio441():
    U1 = np.array([[(0, 0), (1, 0)], [(1, 0), (0, 0)]])
    U2 = np.array([[((2**(1/2))/2, 0), ((2**(1/2))/2, 0)], [((2**(1/2))/2, 0), (-(2**(1/2))/2, 0)]])
    if unitaria(U1) and unitaria(U2):
        print(unitaria(multiplicacion(U1,U2)))
    else: 
        print("false")
Ejercicio441()

false


## Solucion 4.4.2

In [69]:
def dinamicasistema1(munitaria,estado, cl):
    if unitaria(munitaria):
        for i in range(cl):
            estado = accionvecmat(munitaria, estado)
        return estado
    else:
        raise Exception("No se puede realizar la operacion debido a que la matriz no es unitaria")

print(dinamicasistema1([[(0, 0), (1/(2*(1/2)), 0), (1/(2*(1/2)), 0), (0, 0)],
                        [(0,1/(2*(1/2))), (0, 0), (0, 0), (1/(2*(1/2)), 0)],
                        [(1 / (2 * (1 / 2)), 0), (0, 0), (0, 0), (0,1 / (2 * (1 / 2)))],
                        [(0, 0), (1/(2*(1/2)), 0), (-1/(2*(1/2)), 0), (0, 0)]],
                        [(1,0), (0,0), (0,0), (0,0)], 3))


ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (2,4,4)->(2,newaxis,newaxis) (4,4,2)->(4,newaxis,newaxis)  and requested shape (4,2)